# Generated by Django 4.0.2 on 2022-04-13 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_userdata_user_image"),
        ("alert", "0002_alert_home_alert_case_alert_home_alert_death_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification", models.CharField(max_length=300)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.userdata"
                    ),
                ),
            ],
        ),
    ]
