# Generated by Django 4.0.2 on 2022-04-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alert", "0004_alertnotification_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertnotification",
            name="updated",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
