# Generated by Django 4.0.2 on 2022-03-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userdata_email'),
        ('circle', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circleuser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='circleuser',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userdata'),
        ),
        migrations.AlterUniqueTogether(
            name='circleuser',
            unique_together={('circle_id', 'username')},
        ),
        migrations.RemoveField(
            model_name='circleuser',
            name='user_id',
        ),
    ]
