# Generated by Django 4.0.2 on 2022-03-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circle", "0003_alter_circle_admin_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="pending_request",
            field=models.IntegerField(default=0),
        ),
    ]
