# Generated by Django 4.0.2 on 2022-03-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("circle", "0005_requestcircle"),
    ]

    operations = [
        migrations.RemoveField(model_name="circle", name="pending_request",),
    ]
