# Generated by Django 4.0.2 on 2022-03-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circle", "0006_remove_circle_pending_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentCircle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recent_circle", models.TextField(null=True)),
            ],
        ),
    ]
