# Generated by Django 4.0.2 on 2022-03-28 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_userdata_password"),
        ("circle", "0008_recentcircle_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recentcircle",
            name="recent_circle",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="recentcircle",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="login.userdata"
            ),
        ),
    ]
