# Generated by Django 4.0.2 on 2022-04-04 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_alter_userdata_password"),
        ("circle", "0009_alter_recentcircle_recent_circle_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CirclePolicyCompliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "circle_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="circle.circle"
                    ),
                ),
                (
                    "policy_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="circle.policy"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.userdata"
                    ),
                ),
            ],
            options={
                "unique_together": {("circle_id", "policy_id", "username")},
            },
        ),
    ]
