# Generated by Django 4.0.2 on 2022-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circle", "0011_alter_circle_no_of_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="circlepolicycompliance",
            name="compliance",
            field=models.BooleanField(default=False),
        ),
    ]
