# Generated by Django 4.0.2 on 2022-04-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circle", "0016_alter_circle_group_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="group_image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
