# Generated by Django 4.0.2 on 2022-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circle", "0017_alter_circle_group_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="group_image",
            field=models.ImageField(
                default="https://coviguard-images.s3.us-east-1.amazonaws.com/media/default/circle/1.jpg",
                upload_to="media/",
            ),
        ),
    ]
