# Generated by Django 4.0.2 on 2022-04-19 23:13

import circle.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circle", "0022_alter_circle_group_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="circle",
            name="group_image",
            field=models.ImageField(
                default=circle.models.random_img, upload_to="media/circle/"
            ),
        ),
    ]
