# Generated by Django 4.0.2 on 2022-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserData",
            fields=[
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "username",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("dob", models.DateTimeField()),
                ("phone", models.IntegerField(default=9999999999)),
                ("work_address", models.CharField(max_length=200)),
                ("home_adress", models.CharField(max_length=200)),
                ("is_vacinated", models.BooleanField(default=False)),
            ],
        ),
    ]
