# Generated by Django 4.0.2 on 2022-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="email",
            field=models.CharField(default="a@b.com", max_length=100),
        ),
    ]
