# Generated by Django 4.0.2 on 2022-03-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_userdata_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="dob",
            field=models.DateField(),
        ),
    ]
