# Generated by Django 4.0.2 on 2022-03-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_alter_userdata_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="password",
            field=models.CharField(default="coviguard", max_length=50),
        ),
    ]
