# Generated by Django 4.0.2 on 2022-04-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_alter_userdata_dob_alter_userdata_home_adress_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="password",
            field=models.CharField(default="coviguard", max_length=100),
        ),
    ]
