# Generated by Django 4.0.2 on 2022-04-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_alter_userdata_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Privacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("show_vacination", models.BooleanField(default=False)),
                ("show_people_met", models.BooleanField(default=False)),
                ("show_location_visited", models.BooleanField(default=False)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.userdata"
                    ),
                ),
            ],
        ),
    ]
