# Generated by Django 4.0.2 on 2022-04-05 22:51

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_privacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdata",
            name="user_image",
            field=models.ImageField(
                default=login.models.random_img, upload_to="media/user/"
            ),
        ),
    ]
