# Generated by Django 4.0.2 on 2022-05-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_userdata_user_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
            ],
        ),
    ]
