# Generated by Django 4.0.2 on 2022-03-29 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_userdata_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('user_met', models.CharField(max_length=100)),
                ('location_visited', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.userdata')),
            ],
        ),
    ]
