# Generated by Django 4.0.2 on 2022-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selftracking", "0002_selftrack_streak"),
    ]

    operations = [
        migrations.AddField(
            model_name="selftrack",
            name="largest_streak",
            field=models.IntegerField(default=0),
        ),
    ]
