# Generated by Django 4.0.2 on 2022-04-06 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("selftracking", "0003_selftrack_largest_streak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selftrack",
            name="date_uploaded",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
