# Generated by Django 4.0.2 on 2022-04-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selftracking", "0004_alter_selftrack_date_uploaded"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "location_visited",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
