# Generated by Django 4.0.2 on 2022-04-12 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_userdata_user_image"),
        ("selftracking", "0005_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selftrack",
            name="location_visited",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="selftracking.location"
            ),
        ),
        migrations.AlterField(
            model_name="selftrack",
            name="user_met",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_met",
                to="login.userdata",
            ),
        ),
        migrations.AlterField(
            model_name="selftrack",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_input",
                to="login.userdata",
            ),
        ),
    ]
