# Generated by Django 4.0.2 on 2022-04-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_userdata_user_image"),
        ("selftracking", "0007_alter_selftrack_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="selftrack",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="selftrack",
            name="location_visited",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="selftrack",
            name="user_met",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="selftrack",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="login.userdata"
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
