# Generated by Django 4.0.2 on 2022-04-18 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("selftracking", "0008_alter_selftrack_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selftrack",
            name="date_uploaded",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
